[package]
name = "expr-fsm-0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "bench_current_state_enum"
harness = false

[[bench]]
name = "bench_current_state_fn_ptr"
harness = false
